export const Publications = [
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 110,
		"number": "033327",
		"year": 2024,
		"month": 9,
		"title": "Synthetic spin-orbit coupling for the multispin models in optical lattices",
		"authors": "$self, Yan-Qing Zhu, Shanchao Zhang, Shi-Liang Zhu, and Z. D. Wang",
		"authors abbr": "$self, Y.-Q. Zhu, S. Zhang, S.-L. Zhu, and Z. D. Wang",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.110.033327"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 110,
		"number": "023321",
		"year": 2024,
		"month": 8,
		"title": "Synthetic non-Abelian topological charges in ultracold atomic gases",
		"authors": "Qi-Dong Wang, Yan-Qing Zhu, Shi-Liang Zhu, and $self$email",
		"authors abbr": "Q.-D. Wang, Y.-Q. Zhu, S.-L. Zhu, $self$email",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.110.023321"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 107,
		"number": "043304",
		"year": 2023,
		"month": 4,
		"title": "Tunable boson-assisted finite-range interaction and engineering Majorana corner modes in optical lattices",
		"authors": "Yu-Biao Wu, $self$email, Xiang-Gang Qiu, Lin Zhuang, Guang-Can Guo, Xu-Bo Zou, and Wu-Ming Liu",
		"authors abbr": "Y.-B. Wu, $self$email, X.-G. Qiu, L. Zhuang, G.-C. Guo, X.-B. Zou, and W.-M. Liu",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.107.043304"
	},
	{
		"journal": "Physical Review Letters",
		"journal abbr": "Phys. Rev. Lett.",
		"volume": 129,
		"number": 196602,
		"year": 2022,
		"month": 10,
		"title": "Topological Electromagnetic Effects and Higher Second Chern Numbers in Four-Dimensional Gapped Phases",
		"authors": "Yan-Qing Zhu, $self, Giandomenico Palumbo, and Z. D. Wang",
		"authors abbr": "Y.-Q. Zhu, $self, G. Palumbo, and Z. D. Wang",
		"link": "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.129.196602"
	},
	{
		"journal": "Physical Review Letters",
		"journal abbr": "Phys. Rev. Lett.",
		"volume": 128,
		"number": 226401,
		"year": 2022,
		"month": 6,
		"title": "Non-Hermitian Spatial Symmetries and Their Stabilized Normal and Exceptional Topological Semimetals",
		"authors": "W. B. Rui, $self, Chenjie Wang, and Z. D. Wang",
		"authors abbr": "W. B. Rui, $self, C. Wang, and Z. D. Wang",
		"link": "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.128.226401"
	},
	{
		"journal": "npj Quantum Information",
		"journal abbr": "npj Quantum Inf",
		"volume": 8,
		"number": 15,
		"year": 2022,
		"month": 2,
		"title": "Quantum emulation of topological magneto-optical effects using ultracold atoms",
		"authors": "$self and Z. D. Wang",
		"authors abbr": "$self and Z. D. Wang",
		"link": "https://www.nature.com/articles/s41534-022-00529-z"
	},
	{
		"journal": "npj Quantum Materials",
		"journal abbr": "npj Quantum Mater.",
		"volume": 7,
		"number": 15,
		"year": 2022,
		"month": 1,
		"title": "Intertwined Weyl phases emergent from higher-order topology and unconventional Weyl fermions via crystalline symmetry",
		"authors": "W. B. Rui, $self, Moritz M. Hirschmann, Song-Bo Zhang, Chenjie Wang and Z. D. Wang",
		"authors abbr": "W. B. Rui, $self, M. M. Hirschmann, S.-B. Zhang, C. Wang, and Z. D. Wang",
		"link": "https://www.nature.com/articles/s41535-022-00422-0"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 104,
		"number": "013306",
		"year": 2021,
		"month": 7,
		"title": "Multiorder topological superfluid phase transitions in a two-dimensional optical superlattice",
		"authors": "Yu-Biao Wu, Guang-Can Guo, $self$email, and Xu-Bo Zou",
		"authors abbr": "Y.-B. Wu, G.-C. Guo, $self$email, and X.-B. Zou",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.104.013306"
	},
	{
		"journal": "Physical Review B",
		"journal abbr": "Phys. Rev. B",
		"volume": 103,
		"number": 184510,
		"year": 2021,
		"month": 5,
		"title": "Higher-order Weyl superconductors with anisotropic Weyl-point connectivity",
		"authors": "W. B. Rui, Song-Bo Zhang, Moritz M. Hirschmann, $self, Andreas P. Schnyder, Bj&ouml;rn Trauzettel, and Z. D. Wang",
		"authors abbr": "W. B. Rui, S.-B. Zhang, M. M. Hirschmann, $self, A. P. Schnyder, B. Trauzettel, and Z. D. Wang",
		"link": "https://journals.aps.org/prb/abstract/10.1103/PhysRevB.103.184510"
	},
	{
		"journal": "New Journal of Physics",
		"journal abbr": "New J. Phys.",
		"volume": 23,
		"number": "023033",
		"year": 2021,
		"month": 2,
		"title": "Emulation of magneto-optic Faraday effect using ultracold atoms",
		"authors": "$self and Z. D. Wang",
		"authors abbr": "$self and Z. D. Wang",
		"link": "https://iopscience.iop.org/article/10.1088/1367-2630/abdce4"
	},
	{
		"journal": "Journal of Physics: Condensed Matter",
		"journal abbr": "J. Phys.: Condens. Matter",
		"volume": 32,
		"number": 235701,
		"year": 2020,
		"month": 3,
		"title": "Topological supersolidity of dipolar Fermi gases in a spin-dependent optical lattice",
		"authors": "Huan-Yu Wang, $self, Lin Zhuang, Yong-Hang Tai, Jun-Sheng Shi and Wu-Ming Liu",
		"authors abbr": "H.-Y. Wang, $self, L. Zhuang, Y.-H. Tai, J.-S. Shi, and W.-M. Liu",
		"link": "https://iopscience.iop.org/article/10.1088/1361-648X/ab7871"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 101,
		"number": "023612",
		"year": 2020,
		"month": 2,
		"title": "Cavity-induced Fulde-Ferrell-Larkin-Ovchinnikov superfluids of ultracold Fermi gases",
		"authors": "$self and Z. D. Wang",
		"authors abbr": "$self and Z. D. Wang",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.101.023612"
	},
	{
		"journal": "Physical Review Research",
		"journal abbr": "Phys. Rev. Research",
		"volume": 2,
		"number": "013122",
		"year": 2020,
		"month": 2,
		"title": "Locking of symmetry breaking and topological phase in an interacting fermionic wire",
		"authors": "Dan-Bo Zhang, $self, Y. X. Zhao, Qiang-Hua Wang, and Z. D. Wang",
		"authors abbr": "D.-B. Zhang, $self, Y. X. Zhao, Q.-H. Wang, and Z. D. Wang",
		"link": "https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.2.013122"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 101,
		"number": "013622",
		"year": 2020,
		"month": 1,
		"title": "Effective Hamiltonian with tunable mixed pairing in driven optical lattices",
		"authors": "Yu-Biao Wu, Guang-Can Guo, $self$email, and Xu-Bo Zou",
		"authors abbr": "Y.-B. Wu, G.-C. Guo, $self$email, and X.-B. Zou",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.101.013622"
	},
	{
		"journal": "Physical Review Research",
		"journal abbr": "Phys. Rev. Research",
		"volume": 1,
		"number": "033102",
		"year": 2019,
		"month": 11,
		"title": "Chiral magnetic effect in three-dimensional optical lattices",
		"authors": "$self, Zhi Lin, Dan-Wei Zhang, Shi-Liang Zhu, and Z. D. Wang",
		"authors abbr": "$self, Z. Lin, D.-W. Zhang, S.-L. Zhu, and Z. D. Wang",
		"link": "https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.1.033102"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 100,
		"number": "043607",
		"year": 2019,
		"month": 10,
		"title": "Simulation and measurement of topological phase transitions with alkaline-earth-metal atoms in optical lattices",
		"authors": "Bin Wang, Yubiao Wu, $self, and Xubo Zou",
		"authors abbr": "B. Wang, Y. Wu, $self, and X. Zou",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.100.043607"
	},
	{
		"journal": "Journal of Physics B: Atomic, Molecular and Optical Physics",
		"journal abbr": "J. Phys. B: At. Mol. Opt. Phys.",
		"volume": 52,
		"number": "075301",
		"year": 2019,
		"month": 3,
		"title": "Manipulating Cooper pairs with a controllable momentum in periodically driven degenerate Fermi gases",
		"authors": "$self and Z. D. Wang",
		"authors abbr": "$self and Z. D. Wang",
		"link": "https://iopscience.iop.org/article/10.1088/1361-6455/ab08df"
	},
	{
		"journal": "New Journal of Physics",
		"journal abbr": "New J. Phys.",
		"volume": 20,
		"number": "063001",
		"year": 2018,
		"month": 6,
		"title": "Fulde-Ferrell superfluids in spinless ultracold Fermi gases",
		"authors": "Zhen-Fei Zheng, Guang-Can Guo, $self$email and Xu-Bo Zou",
		"authors abbr": "Z.-F. Zheng, G.-C. Guo, $self$email, and X.-B. Zou",
		"link": "https://iopscience.iop.org/article/10.1088/1367-2630/aac7f1"
	},
	{
		"journal": "New Journal of Physics",
		"journal abbr": "New J. Phys.",
		"volume": 20,
		"number": "023039",
		"year": 2018,
		"month": 2,
		"title": "Synthetic topological Kondo insulator in a pumped optical cavity",
		"authors": "$self, Xu-Bo Zou and Guang-Can Guo",
		"authors abbr": "$self, X.-B. Zou and G.-C. Guo",
		"link": "https://iopscience.iop.org/article/10.1088/1367-2630/aaaa50"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 95,
		"number": "013616",
		"year": 2017,
		"month": 1,
		"title": "Artificial topological models based on a one-dimensional spin-dependent optical lattice",
		"authors": "$self, Han Pu, Xubo Zou, and Guangcan Guo",
		"authors abbr": "$self, H. Pu, X. Zou, and G. Guo",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.95.013616"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 93,
		"number": "031602(R)",
		"year": 2016,
		"month": 3,
		"title": "Effective <i>p</i>-wave interaction and topological superfluids in <i>s</i>-wave quantum gases",
		"authors": "Bin Wang, $self, Han Pu, Xubo Zou, and Guangcan Guo",
		"authors abbr": "B. Wang, $self, H. Pu, X. Zou, and G. Guo",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.93.031602"
	},
	{
		"journal": "Physical Review Letters",
		"journal abbr": "Phys. Rev. Lett.",
		"volume": 116,
		"number": 120403,
		"year": 2016,
		"month": 3,
		"title": "Fulde-Ferrell Superfluids without Spin Imbalance in Driven Optical Lattices",
		"authors": "$self, Chunlei Qu, Xubo Zou, and Chuanwei Zhang",
		"authors abbr": "$self, C. Qu, X. Zou, and C. Zhang",
		"link": "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.116.120403"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 91,
		"number": "063626",
		"year": 2015,
		"month": 6,
		"title": "Floquet Fulde-Ferrell-Larkin-Ovchinnikov superfluids and Majorana fermions in a shaken fermionic optical lattice",
		"authors": "$self, Chunlei Qu, Xubo Zou, and Chuanwei Zhang",
		"authors abbr": "$self, C. Qu, X. Zou, and C. Zhang",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.91.063626"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 90,
		"number": "063623",
		"year": 2014,
		"month": 12,
		"title": "Thermodynamic properties of Rashba spin-orbit-coupled Fermi gas",
		"authors": "$self, Han Pu, Xubo Zou, and Guangcan Guo",
		"authors abbr": "$self, H. Pu, X. Zou, and G. Guo",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.90.063623"
	},
	{
		"journal": "Scientific Reports",
		"journal abbr": "Sci. Rep.",
		"volume": 4,
		"number": 6535,
		"year": 2014,
		"month": 10,
		"title": "FFLO Superfluids in 2D Spin-Orbit Coupled Fermi Gases",
		"authors": "$self, Ming Gong, Yichao Zhang, Xubo Zou, Chuanwei Zhang, and Guangcan Guo ",
		"authors abbr": "$self, M. Gong, Y. Zhang, X. Zou, C. Zhang, and G. Guo",
		"link": "https://www.nature.com/articles/srep06535"
	},
	{
		"journal": "Nature Communications",
		"journal abbr": "Nat. Commun.",
		"volume": 4,
		"number": 2710,
		"year": 2013,
		"month": 10,
		"title": "Topological superfluids with finite-momentum pairing and Majorana fermions",
		"authors": "Chunlei Qu, $self, Ming Gong, Yong Xu, Li Mao, Xubo Zou, Guangcan Guo, and Chuanwei Zhang",
		"authors abbr": "C. Qu, $self, M. Gong, Y. Xu, L. Mao, X. Zou, G. Guo, and C. Zhang",
		"link": "https://www.nature.com/articles/ncomms3710"
	},
	{
		"journal": "Physical Review A",
		"journal abbr": "Phys. Rev. A",
		"volume": 87,
		"number": "031602(R)",
		"year": 2013,
		"month": 3,
		"title": "Route to observable Fulde-Ferrell-Larkin-Ovchinnikov phases in three-dimensional spin-orbit-coupled degenerate Fermi gases",
		"authors": "$self, Ming Gong, Xubo Zou, Chuanwei Zhang, and Guangcan Guo",
		"authors abbr": "$self, M. Gong, X. Zou, C. Zhang, and G. Guo",
		"link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.87.031602"
	}
];
